// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtB6tcrEwghN2e4Acy07Ir02cmW3BA0y0',
    appId: '1:459423427746:web:75cbaf1a9bdd74fe44bbfb',
    messagingSenderId: '459423427746',
    projectId: 'farmer-buyer-app-d934d',
    authDomain: 'farmer-buyer-app-d934d.firebaseapp.com',
    storageBucket: 'farmer-buyer-app-d934d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBYcty2OGmxmUg0yqmXCWNkRdW7drLf4',
    appId: '1:459423427746:android:609af5bcb51ad99a44bbfb',
    messagingSenderId: '459423427746',
    projectId: 'farmer-buyer-app-d934d',
    storageBucket: 'farmer-buyer-app-d934d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlBq9gH8ZtA-d9502Vu09swaOL72nY3BI',
    appId: '1:459423427746:ios:899422126ed7463544bbfb',
    messagingSenderId: '459423427746',
    projectId: 'farmer-buyer-app-d934d',
    storageBucket: 'farmer-buyer-app-d934d.firebasestorage.app',
    iosBundleId: 'com.example.farmerBuyerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlBq9gH8ZtA-d9502Vu09swaOL72nY3BI',
    appId: '1:459423427746:ios:899422126ed7463544bbfb',
    messagingSenderId: '459423427746',
    projectId: 'farmer-buyer-app-d934d',
    storageBucket: 'farmer-buyer-app-d934d.firebasestorage.app',
    iosBundleId: 'com.example.farmerBuyerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtB6tcrEwghN2e4Acy07Ir02cmW3BA0y0',
    appId: '1:459423427746:web:871288e6e51b033d44bbfb',
    messagingSenderId: '459423427746',
    projectId: 'farmer-buyer-app-d934d',
    authDomain: 'farmer-buyer-app-d934d.firebaseapp.com',
    storageBucket: 'farmer-buyer-app-d934d.firebasestorage.app',
  );
}
